### ISSUE TITLE
[feat] ErrorCode, SuccessCode 생성

### ISSUE THREAD

**Issue by ykim-yeji** [ReBing23/PicStage-Backend#2]
## ✅ Checklist
- [ ] 이슈 제목 작성 [feature] 개발할 기능

## ✏️ Description
- 사용할 errorcode 상수 작성
- 사용할 successcode 상수 작성

## 📋 TODO
- [ ] enum 클래스 생성
- [ ] errorcode 종류 작성
- [ ] successcode 종류 작성
